### ISSUE TITLE
migration from setInputBoxConstraints and setStateBoxConstraints to setBoxConstraints

### ISSUE THREAD

**Issue by tcozic** [ethz-adrl/ct_ros#1]
Hi, 
Some executable example don't build with control-toolbox v3.0.2(HyANLOC_ObstacleAcc.cpp, HyANLOC_TaskSpaceVel.cpp, HyANLOC_TaskSpace.cpp, HyADMS.cpp and HyANLOC_TaskSpaceAcc.cpp),
They use setInputBoxConstraints() and setStateBoxConstraints() to set 'ContinuousOptConProblem' which do not exist. I used the following solution to make it build, is it correct ?
```cpp 
//HyQSimulator.cpp line 138
    std::shared_ptr<ct::optcon::ConstraintContainerAnalytical<state_dim, control_dim>> boxConstraints(
        new ct::optcon::ConstraintContainerAnalytical<state_dim, control_dim>());

    // input constraint bounds
    ct::core::ControlVector<control_dim> u_lb = -100 * ct::core::ControlVector<control_dim>::Ones();
    ct::core::ControlVector<control_dim> u_ub = 100 * ct::core::ControlVector<control_dim>::Ones();
    // input constraint terms
    std::shared_ptr<ct::optcon::ControlInputConstraint<state_dim, control_dim>> controlConstraint(
        new ct::optcon::ControlInputConstraint<state_dim, control_dim>(u_lb, u_ub));
    controlConstraint->setName("ControlInputConstraint");
    
    // state constraint bounds
    ct::core::StateVector<state_dim> x_lb, x_ub;
    x_lb.head<njoints>() = -3.14 * Eigen::Matrix<double, njoints, 1>::Ones(); // lower bound on position
    x_ub.head<njoints>() =  3.14 * Eigen::Matrix<double, njoints, 1>::Ones(); // upper bound on position
    x_lb.tail<njoints>() = -100 * Eigen::Matrix<double, njoints, 1>::Ones(); // lower bound on velocity
    x_ub.tail<njoints>() =  100 * Eigen::Matrix<double, njoints, 1>::Ones(); // upper bound on velocity
    // state constraint terms
    std::shared_ptr<ct::optcon::StateConstraint<state_dim, control_dim>> stateConstraint(
        new ct::optcon::StateConstraint<state_dim, control_dim>(x_lb, x_ub));
    stateConstraint->setName("StateConstraint");
    // add and initialize constraint terms    
    boxConstraints->addIntermediateConstraint(controlConstraint, true);
    boxConstraints->addIntermediateConstraint(stateConstraint, true);
    boxConstraints->addTerminalConstraint(stateConstraint,true);
    boxConstraints->initialize();
```

**Comment by markusgft** [comment]
Dear @tcozic v3.0.2 has not been released officially yet -- in fact, v3.0.2 is currently identical to 3.0.1.

If you are interested in working with the latest versions, then please checkout out branch devel in the control_toolbox repo, and branch feature/devel here in ct_ros. If you choose to do this, you may want to run the install scripts in control_toolbox/ct, e.g. install_deps.sh, install_hpipm.sh and install_cppadcg.sh!

Otherwise, I would recommend to go to 3.0.1 in control toolbox and master in ct_ros.

If that does not resolve your problem, you probably have an older version of the control toolbox installed globally on your system, and I would then recommend deleting the related folders in /usr/include/ct, /usr/share/ct.

**Comment by tcozic** [comment]
Even when using 3.0.1 (my ct_ros branch is master) I encounter the same issue, the following functions don't exist in the ContinuousOptConProblem class (or OptConProblemBase, or in the control-toolbox repositories at all...).:
```cpp
    optConProblem.setInputBoxConstraints(inputBoxConstraints);
    optConProblem.setStateBoxConstraints(stateBoxConstraints);
```

![CuildCTROS](https://user-images.githubusercontent.com/29738996/69036049-50718880-09e5-11ea-865f-5d0cadc4d187.png)

I have nothing my /usr/include or /usr/share related to the control-toolbox.

**Comment by markusgft** [comment]
Can you switch to the devel branches and give this a try? I will release
v302 soon, but I am currently traveling.
You may need to forward your hpipm version!

**Comment by tcozic** [comment]
With devel branch, it solves the problem, but I had to desactivate the build of HyA_NLP_IK :
```
error: no matching function for call to ‘ct::rbd::Kinematics<ct::rbd::RobCoGenContainer<iit::ct_HyA::tpl::Traits<CppAD::AD<CppAD::cg::CG<double> > >, iit::ct_HyA::LinkDataMap, ct::rbd::HyA::Utils<CppAD::AD<CppAD::cg::CG<double> > > >, 1>::getEEPositionInWorld(size_t&, ct::rbd::RBDState<6, double>::RigidBodyPose_t&, ct::rbd::JointState<6, double>::JointPositionBlock)’
```
Nice work with the packages by the way.

**Comment by markusgft** [comment]
Hi @tcozic that error should not have appeared with the current version of the devel branch ... did you pull before building?

**Comment by tcozic** [comment]
Hi, Everything seems fine now, thanks for the help with the package.
